# docker-compose.yml
version: '3.8'

services:
  api:
    # MUDANÇA AQUI: Aponta para a pasta ./backend para encontrar o Dockerfile
    build: ./backend
    container_name: api_reservas
    ports:
      - "3000:3000"
    #volumes:
      # MUDANÇA AQUI: Mapeia a pasta ./backend para o contêiner
      #- ./backend:/usr/src/app
      #- /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db: # Esta parte não muda
    image: postgres:15-alpine
    container_name: db_reservas
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: