
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_reservas
    ports:
      - "3000:3000"
    volumes:

      - ./backend/src:/app/src
      - ./backend/server.js:/app/server.js
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    container_name: db_reservas
    env_file:
      - ./.env
    volumes:
      # Mantém os dados do banco salvos entre reinicializações
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"


volumes:
  postgres_data: