
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_reservas
    ports:
      - "3000:3000"
    volumes:

      - ./backend/src:/app/src
      - ./backend/server.js:/app/server.js
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: db_reservas
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

volumes:
  postgres_data: